/**
 * 颜色枚举
 */
export enum Colors {
  blue = '#08c',
  cyan = '#1bc',
  green = '#3c1',
  yellow = '#db1',
  orange = '#f73',
  red = '#e43',
  pink = '#e5b',
  purple = '#94e',
  grey = '#999',
  black = '#2a2a2a',
}
/**
 * 图标枚举
 */
export enum Icons {
  airbnb = 'airbnb',
  alipay = 'alipay',
  aliwangwang = 'aliwangwang',
  aliyun = 'aliyun',
  amazon = 'amazon',
  android = 'android',
  antd = 'antd',
  apple = 'apple',
  appveyor = 'appveyor',
  atom = 'atom',
  awesome = 'awesome',
  badg = 'badg',
  behance = 'behance',
  bitcoin = 'bitcoin',
  'bitcoin-lightning' = 'bitcoin-lightning',
  chrome = 'chrome',
  circleci = 'circleci',
  'code-sandbox' = 'code-sandbox',
  codebeat = 'codebeat',
  codeclimate = 'codeclimate',
  codecov = 'codecov',
  codepen = 'codepen',
  codeship = 'codeship',
  commonwl = 'commonwl',
  deepscan = 'deepscan',
  dependabot = 'dependabot',
  dingding = 'dingding',
  discord = 'discord',
  dockbit = 'dockbit',
  docker = 'docker',
  dropbox = 'dropbox',
  eclipse = 'eclipse',
  email = 'email',
  facebook = 'facebook',
  firefox = 'firefox',
  flow = 'flow',
  git = 'git',
  gitee = 'gitee',
  github = 'github',
  gitlab = 'gitlab',
  gitter = 'gitter',
  google = 'google',
  'google-plus' = 'google-plus',
  googleplay = 'googleplay',
  graphql = 'graphql',
  haskell = 'haskell',
  instagram = 'instagram',
  kofi = 'kofi',
  lgtm = 'lgtm',
  libraries = 'libraries',
  linkedin = 'linkedin',
  now = 'now',
  npm = 'npm',
  nuget = 'nuget',
  patreon = 'patreon',
  phone = 'phone',
  postgresql = 'postgresql',
  qq = 'qq',
  rss = 'rss',
  ruby = 'ruby',
  scrutinizer = 'scrutinizer',
  segmentfault = 'segmentfault',
  sketch = 'sketch',
  skype = 'skype',
  slack = 'slack',
  sourcegraph = 'sourcegraph',
  stackoverflow = 'stackoverflow',
  telegram = 'telegram',
  terminal = 'terminal',
  terraform = 'terraform',
  travis = 'travis',
  twitter = 'twitter',
  typescript = 'typescript',
  wechat = 'wechat',
  weibo = 'weibo',
  windows = 'windows',
  youtube = 'youtube',
  yuque = 'yuque',
  zeit = 'zeit',
  zhihu = 'zhihu',
}

/**
 * 字符宽度
 */
export const chars = {
  a: 66,
  b: 69,
  c: 57,
  d: 69,
  e: 66,
  f: 39,
  g: 69,
  h: 70,
  i: 30,
  j: 38,
  k: 65,
  l: 30,
  m: 110,
  n: 70,
  o: 67,
  p: 69,
  q: 69,
  r: 47,
  s: 57,
  t: 43,
  u: 70,
  v: 65,
  w: 90,
  x: 65,
  y: 65,
  z: 58,
  A: 75,
  B: 75,
  C: 77,
  D: 85,
  E: 70,
  F: 63,
  G: 85,
  H: 83,
  I: 46,
  J: 50,
  K: 76,
  L: 61,
  M: 93,
  N: 82,
  O: 87,
  P: 66,
  Q: 87,
  R: 76,
  S: 75,
  T: 68,
  U: 81,
  V: 75,
  W: 110,
  X: 75,
  Y: 68,
  Z: 75,
  ' ': 39,
  '!': 43,
  '"': 50,
  '%': 120,
  $: 70,
  '#': 90,
  '&': 80,
  '\'': 30,
  '(': 50,
  ')': 50,
  '*': 70,
  '+': 90,
  ',': 40,
  '-': 50,
  '/': 50,
  ':': 50,
  ';': 50,
  '<': 90,
  '=': 90,
  '>': 90,
  '?': 60,
  '@': 110,
  '[': 50,
  '\\': 50,
  ']': 50,
  '^': 90,
  _: 70,
  '`': 70,
  '{': 70,
  '|': 50,
  '}': 70,
  '~': 90,
  0: 70,
  '.': 40,
};
