export default {
  tag: "Latest tag",
  "open-issues": "Open issues",
  "closed-issues": "Closed issues",
  "label-issues": (query) => query.param,
  "open-label-issues": (query) => query.param,
  "closed-label-issues": (query) => query.param,
  prs: "PRs",
  "open-prs": "Open PRs",
  "closed-prs": "Closed PRs",
  "merged-prs": "Merged PRs",
  milestones: (query) => query.param,
  "last-commit": "Last commit",
  "last-commit-branch": (query) => `Last commit (${query.param})`,
  "last-commit-tag": (query) => `Last commit (${query.param})`,
  commits: (query) => `Commits${query.param ? ` (${query.param})` : ""}`,
};
